import { Signika_Negative } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import Footer from "@/components/Footer";
import { ToastContainer} from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';

const signikaNegative = Signika_Negative({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-signikaNegative",
});

export const metadata = {
  title: "6ix-Kicks",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={signikaNegative.variable}>
        <Header />
        {children}
        <ToastContainer position="top-center" hideProgressBar={true} closeOnClick pauseOnHover={false} newestOnTop={true} style={{ width: 'fit-content' }}/>
        <Footer />
      </body>
    </html>
  );
}
